spring:
  application:
    name: group-service
  cloud:
    compatibility-verifier:
      enabled: false
server:
  port: 0
  servlet:
    context-path: /v1/api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
jwt:
  secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
