spring.application.name=GROUP-SERVICE
spring.cloud.compatibility-verifier.enabled=false
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.url=jdbc:sqlserver://LAPTOP-H3B9DDNO:1433;databaseName=LabVerse_Group_Service;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

server.port=0

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:9001/eureka/
#  ,http://localhost:9002/eureka/,http://localhost:9003/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

# Eureka Health Check URL (phải include context-path)
eureka.instance.health-check-url-path=/v1/api/actuator/health

# Context path
server.servlet.context-path=/v1/api

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
management.health.defaults.enabled=true