spring.application.name=READING-WORKFLOW-SERVICE

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LabVerse_Reading_Service;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Use 'create' or 'create-drop' to recreate table, or 'update' after running migration script
spring.jpa.hibernate.ddl-auto=update

server.port=0

# Context path removed - Gateway will handle routing
# server.servlet.context-path=/api/reading

eureka.client.service-url.defaultZone=http://localhost:9001/eureka/,http://localhost:9002/eureka/,http://localhost:9003/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance-id:${random.value}}

########################################
# ? SWAGGER (SPRINGDOC)
########################################
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

