spring.application.name=Reading Service

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://LAPTOP-H3B9DDNO:1433;databaseName=LabVerse_Reading_Service;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

server.port=0
server.servlet.context-path=/v1/api

eureka.client.service-url.defaultZone=http://localhost:9001/eureka/,http://localhost:9002/eureka/,http://localhost:9003/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

