### Get details information of a citation
@url = http://localhost:8080/v1/api/citations
@id = ZjkzMjk3YTItZmM4Yi00MWE4LTgxNTgtNjhkNTQ0OWRjYzA4

GET {{url}}/{{id}}
Accept: application/json

###
HEAD {{url}}/health

