@url = http://localhost:8080/v1/api/papers

### Get paper details
@id = YjNjZGU2YTUtYWYyYi00ZDJjLTljYWYtN2UxODY3ZDY3OWI4
GET {{url}}/details?id={{id}}
Accept: application/json


### Get references
GET {{url}}/references?id={{id}}
Accept: application/json

### Parse citations
POST {{url}}/pdf/parse
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: application/json

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Phishing_Emails_Detection_in_Cyber_Security.pdf"
Content-Type: application/pdf

< ./Phishing_Emails_Detection_in_Cyber_Security.pdf
--WebAppBoundary--

### Upload pdf metadata with happy case
POST {{url}}/pdf/upload
Content-Type: application/json
Accept: application/json

{
  "dataUrl": "http://localhost:8080/hehe",
  "description": "description",
  "keywords": [
    "kw1", "kw2", "kw3"
  ],
  "title": "title1",
  "authors": "Author1, author 2",
  "journal": "Journal",
  "publicationYear": 2021,
  "doi": "10.34190/iccws.20.1.3366"
}

### Upload pdf metadata with wrong format doi case
POST {{url}}/pdf/upload
Content-Type: application/json
Accept: application/json

{
  "dataUrl": "http://localhost:8080/hehe",
  "description": "description",
  "keywords": [
    "kw1", "kw2", "kw3"
  ],
  "title": "title1",
  "authors": "Author1, author 2",
  "journal": "Journal",
  "publicationYear": 2021,
  "doi": "10.3419ccws.20.1.3366"
}

### Upload pdf metadata with wrong format uri case
POST {{url}}/pdf/upload
Content-Type: application/json
Accept: application/json

{
  "dataUrl": "http://ocal:8/hhe",
  "description": "description",
  "keywords": [
    "kw1", "kw2", "kw3"
  ],
  "title": "title1",
  "authors": "Author1, author 2",
  "journal": "Journal",
  "publicationYear": 2021,
  "doi": "10.34190/iccws.20.1.3369"
}

### Ping api
HEAD {{url}}/health

### Advanced Search - General query search
POST {{url}}/all
Content-Type: application/json
Accept: application/json

{
  "query": "machine learning",
  "pageIndex": 0,
  "pageSize": 10
}

### Advanced Search - Search by title
POST {{url}}/all
Content-Type: application/json
Accept: application/json

{
  "title": "Phishing",
  "pageIndex": 0,
  "pageSize": 10
}

### Advanced Search - Search by authors
POST {{url}}/all
Content-Type: application/json
Accept: application/json

{
  "authors": "Author1",
  "pageIndex": 0,
  "pageSize": 10
}

### Advanced Search - Search by journal
POST {{url}}/all
Content-Type: application/json
Accept: application/json

{
  "journal": "Journal",
  "pageIndex": 0,
  "pageSize": 10
}

### Advanced Search - Search by keywords
POST {{url}}/all
Content-Type: application/json
Accept: application/json

{
  "keywords": ["kw1", "kw2"],
  "pageIndex": 0,
  "pageSize": 10
}

### Advanced Search - Search by year range
POST {{url}}/all
Content-Type: application/json
Accept: application/json

{
  "yearFrom": 2020,
  "yearTo": 2023,
  "pageIndex": 0,
  "pageSize": 10
}

### Advanced Search - Complex search with multiple filters
POST {{url}}/all
Content-Type: application/json
Accept: application/json

{
  "query": "machine learning",
  "title": "neural",
  "yearFrom": 2020,
  "yearTo": 2024,
  "keywords": ["deep learning", "ai"],
  "pageIndex": 0,
  "pageSize": 20,
  "sortBy": "publicationYear",
  "sortOrder": "desc"
}

### Advanced Search - Search with tags
POST {{url}}/all
Content-Type: application/json
Accept: application/json

{
  "tagIds": ["tag-id-1", "tag-id-2"],
  "pageIndex": 0,
  "pageSize": 10
}

### Advanced Search - Search with sorting by title
POST {{url}}/all
Content-Type: application/json
Accept: application/json

{
  "query": "security",
  "pageIndex": 0,
  "pageSize": 10,
  "sortBy": "title",
  "sortOrder": "asc"
}

### Advanced Search - No filters (get all papers)
POST {{url}}/all
Content-Type: application/json
Accept: application/json

{
  "pageIndex": 0,
  "pageSize": 10
}