@url = http://localhost:8080/v1/api/tags

### Get tags by paper
@id = YjNjZGU2YTUtYWYyYi00ZDJjLTljYWYtN2UxODY3ZDY3OWI4
GET {{url}}/paper/{{id}}
Accept: application/json

###
POST http://localhost:8080/v1/api/papers/pdf/parse
Content-Type: multipart/form-data

###
GET {{url}}